version: '3.9'

services:
  backend:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
      - ./database.json:/usr/src/app/database.json
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    command: npm run start:backend
    environment:
      - NODE_ENV=development
      - GOOGLE_GEN_AI_KEY=${GOOGLE_GEN_AI_KEY}

  frontend:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: npm run start:frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
